services:
  postgres:
    image: postgres:17.4
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: projeto_software
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      DATABASE_URL: "postgresql://user:user@postgres:5433/projeto_software?schema=public"
      JWT_SECRET: "37 bv6sWlL!%w*3eXejSINfzF)(F.{;s"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: >
      sh -c "
      npm run migrate &&
      npm run seed &&
      npm run start
      "

volumes:
  postgres_data:
